---
title: "reg"
author: "Gabriela García Velásquez"
date: "`r Sys.Date()`"
output:
  pdf_document:
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Regresión Regularizada (Ridge / Lasso) para PM10

```{r}

library(glmnet)
library(dplyr)
library(ggplot2)

archivos = c(
  "NE2_semanal_mediana_con_ndvi_sin_nulos.csv",
  "NE3_semanal_mediana_con_ndvi_sin_nulos.csv"
)


lista_df = lapply(archivos, read.csv)
df = bind_rows(lista_df)
str(df)
colSums(is.na(df))

```

```{r}


# Y = PM10 
# X = meteorología + NDVI + estación (dummy)
variables_modelo = c("PM10", "WSR", "WDR_E", "WDR_N", "WDR_NE", "WDR_NO",
                       "WDR_O", "WDR_S", "WDR_SE", "TOUT", "RH", "SR",
                      "PRS", "RAINF", "ndvi_mediana", "estacion")

df_modelo = df %>% select(all_of(variables_modelo))
df_modelo = na.omit(df_modelo)

```

```{r}

# Preparar variable dummy de estación y matriz de diseño
# model.matrix crea automáticamente las dummies para 'estacion'
# El -1 en la fórmula evita que se agregue un intercepto duplicado en X
X = model.matrix(PM10 ~ . - 1, data = df_modelo)
y = df_modelo$PM10

```

```{r}

# estandarización de variables
# glmnet estandariza internamente por defecto (standardize = TRUE),
#división train y test
set.seed(123)  # para reproducibilidad
n = nrow(X)
indices_train = sample(1:n, size = floor(0.8 * n))

X_train = X[indices_train, ]
y_train = y[indices_train]
X_test  = X[-indices_train, ]
y_test  = y[-indices_train]
```



## validación cruzada
```{r}
# LASSO
cv_lasso = cv.glmnet(X_train, y_train, alpha = 1, standardize = TRUE)
par(mar = c(5, 4, 6, 2) + 0.1) 
plot(cv_lasso)
title(main = "Selección de λ por Validación Cruzada — Modelo Lasso (PM10)", line = 3)  # muestra el error según lambda
lambda_lasso_optimo = cv_lasso$lambda.min

# RIDGE
cv_ridge = cv.glmnet(X_train, y_train, alpha = 0, standardize = TRUE)
plot(cv_ridge)
lambda_ridge_optimo = cv_ridge$lambda.min

```

## Ajuste del modelo con lambdas

```{r}

modelo_lasso = glmnet(X_train, y_train, alpha = 1, lambda = lambda_lasso_optimo,
                        standardize = TRUE)
modelo_ridge = glmnet(X_train, y_train, alpha = 0, lambda = lambda_ridge_optimo,
                        standardize = TRUE)
```

## coeficientes
```{r}

# En Lasso, los coeficientes muy pequeños se eliminan
#  esto es la selección de variables automática
print("Coeficientes LASSO:")
print(coef(modelo_lasso))

print("Coeficientes RIDGE:")
print(coef(modelo_ridge))

```


## evaluación de desempeño
```{r}

pred_lasso = predict(modelo_lasso, newx = X_test)
pred_ridge = predict(modelo_ridge, newx = X_test)

rmse = function(real, pred) sqrt(mean((real - pred)^2))
r2   = function(real, pred) 1 - sum((real - pred)^2) / sum((real - mean(real))^2)

cat("LASSO -> RMSE:", rmse(y_test, pred_lasso), " | R2:", r2(y_test, pred_lasso), "\n")
cat("RIDGE -> RMSE:", rmse(y_test, pred_ridge), " | R2:", r2(y_test, pred_ridge), "\n")

```

## diagnóstico de residuos

```{r}

residuos = y_test - as.vector(pred_lasso)

variables_meteo = c("WSR", "WDR_E", "WDR_N", "WDR_NE", "WDR_NO",
                       "WDR_O", "WDR_S", "WDR_SE", "TOUT", "RH", "SR", "PRS", "RAINF")

par(mfrow = c(2, 4))  
for (var in variables_meteo) {
  plot(df_modelo[-indices_train, var], residuos,
       xlab = var, ylab = "Residuos",
       main = paste("Residuos vs", var),
       pch = 19, col = rgb(0, 0, 1, 0.4))
  abline(h = 0, col = "red", lty = 2)
}
par(mfrow = c(1, 1)) 

residuosr = y_test - as.vector(pred_ridge)

par(mfrow = c(2, 4))  
for (var in variables_meteo) {
  plot(df_modelo[-indices_train, var], residuosr,
       xlab = var, ylab = "Residuos",
       main = paste("Residuos vs", var),
       pch = 19, col = rgb(0, 0, 1, 0.4))
  abline(h = 0, col = "red", lty = 2)
}
par(mfrow = c(1, 1)) 
```

